import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Manuale } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
});

const manuale = Manuale({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-manuale",
});
export const metadata: Metadata = {
  title: "AFF supplyRoot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${manuale.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
