import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Manuale } from "next/font/google";
import ToastProvider from "@/components/ToastProvider";
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
});

const manuale = Manuale({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-manuale",
});
export const metadata: Metadata = {
  title: "AFF supplyRoot",
  description: "Generated by create next app",
    icons: {
    icon: "../../public/logo.svg", // ảnh logo (favicon)
    shortcut: "../../public/logo.svg", // optional
    apple: "../../public/logo.svg", // cho iOS
  },
  openGraph: {
    title: "AFF supplyRoot",
    description: "Generated by create next app",
    images: ["../../public/logo.svg"], // ảnh share mạng xã hội
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${manuale.variable}`}
      >
        <ToastProvider>
          <main>{children}</main>
        </ToastProvider>

      </body>
    </html>
  );
}
